[tool.pylint."messages control"]
disable = [
    'missing-module-docstring',
    'missing-class-docstring',
    'missing-function-docstring',
    'invalid-name',
    'too-many-instance-attributes',
    'too-few-public-methods',
    'too-many-arguments',
    'too-many-positional-arguments',
    'unused-argument',
    'too-many-public-methods',
    'too-many-return-statements',
    'too-many-lines',
    'too-many-locals',
    'too-many-boolean-expressions',
]
